version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  node:
    restart: always
    depends_on:
      - "mongo"
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/code
    environment:
      - MONGO_URI=mongodb://mongo:27017/test      
volumes:
 mongodb: